# Generated by Django 3.2.1 on 2021-05-05 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_creacion')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_modificacion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('ano', models.SmallIntegerField()),
                ('serial', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=30)),
                ('dimensiones', models.IntegerField(default=0)),
                ('riesgos', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=400)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_creacion')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_modificacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_creado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_creacion')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_modificacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_creado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_creacion')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_modificacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_creado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_creacion')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_modificacion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='nombre')),
                ('notas', models.CharField(max_length=100, verbose_name='notas')),
                ('categoria', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('FATAL', 'FATAL'), ('SUCCESS', 'SUCCESS')], max_length=100, verbose_name='categoria')),
                ('severidad', models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], max_length=100, verbose_name='severidad')),
                ('actor_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='id_actor')),
                ('actor_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email_actor')),
                ('actor_nombre', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='nombre_actor')),
                ('anonimo', models.BooleanField(default=False, verbose_name='anonimo')),
                ('propiedades', models.TextField(blank=True, null=True, verbose_name='propiedades')),
                ('origen', models.CharField(blank=True, choices=[('EQUIPO_MEDICO', 'EQUIPO_MEDICO'), ('USUARIO', 'USUARIO'), ('TERCERO', 'TERCERO')], max_length=20, null=True, verbose_name='origen')),
                ('target_id', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True, verbose_name='fecha_evento')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip_origen')),
                ('meta_datos', models.TextField(blank=True, null=True, verbose_name='meta_datos')),
                ('es_una_prueba', models.BooleanField(default=False, verbose_name='es_prueba')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_creado_por', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.tipo'),
        ),
    ]
